dist: trusty
sudo: false
language: java
jdk:
  - oraclejdk8
git:
  depth: 3
before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
install: true
script:
  - sudo add-apt-repository -y ppa:elt/libsodium
  - sudo apt-get update
  - sudo apt-get install -y autoconf automake libtool make tar gcc-multilib libaio-dev libsodium-dev
  - gradle build
  - gradle test --stacktrace --info
notifications:
  email: false
