version: '3'
services:
  nginx:
    depends_on:
      - orion_1
      - orion_2
    image: nginx:latest
    container_name: load_balancer
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 8080:8080
      - 8888:8888
  postgres:
    image: postgres:12
    container_name: postgres
    ports:
      - 5432
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
  orion_1:
    depends_on:
      - postgres
    image: $DOCKER_IMAGE
    container_name: orion_1
    volumes:
      - ./orion.conf:/etc/orion.conf
      - ./keys:/var/keys
    command: /etc/orion.conf
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/upcheck"]
      interval: 10s
      timeout: 10s
      retries: 10
  orion_2:
    image: $DOCKER_IMAGE
    container_name: orion_2
    volumes:
      - ./orion.conf:/etc/orion.conf
      - ./keys:/var/keys
    command: /etc/orion.conf
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/upcheck"]
      interval: 10s
      timeout: 10s
      retries: 10
